/* eslint-disable @typescript-eslint/no-magic-numbers */
import {TechId} from '@src/models/resources';

export const Tech = {
  MetalMine: 1 as TechId,
  CrystalMine: 2 as TechId,
  DeuteriumSynthesizer: 3 as TechId,
  SolarPlant: 4 as TechId,
  RoboticsFactory: 14 as TechId,
  NaniteFactory: 15 as TechId,
  Shipyard: 21 as TechId,
  MetalStorage: 22 as TechId,
  CrystalStorage: 23 as TechId,
  DeuteriumStorage: 24 as TechId,
  ResearchLaboratory: 31 as TechId,
  MissileSilo: 44 as TechId,
  TransporterSmall: 202 as TechId,
  TransporterLarge: 203 as TechId,
  ColonyShip: 208 as TechId,
  Recycler: 209 as TechId,
  EspionageProbe: 210 as TechId,
  SolarSatellite: 212 as TechId,
  RocketLauncher: 401 as TechId,
  LaserCannonHeavy: 403 as TechId,
  GaussCannon: 404 as TechId,
  PlasmaCannon: 406 as TechId,
  ShieldDomeSmall: 407 as TechId,
  ShieldDomeLarge: 408 as TechId,
  MissileInterceptor: 502 as TechId,
};
