import {BuildItem} from '@shared/models/build_item';
import {
  CrystalMine,
  DeuteriumSynthesizer,
  MetalMine,
  ResearchLab,
  RoboticsFactory,
  Shipyard,
} from '@shared/models/building';
import {PlanetId} from '@shared/models/planet';
import {SmallCargo} from '@shared/models/ships';
import {CombustionDrive, EnergyTechnology} from '@shared/models/technology';

export function getBest(planetId: PlanetId): BuildItem[] {
  return [
    {type: 'building', buildable: MetalMine, level: 1, planetId},
    {type: 'building', buildable: MetalMine, level: 2, planetId},
    {type: 'building', buildable: MetalMine, level: 3, planetId},
    {type: 'building', buildable: MetalMine, level: 4, planetId},
    {type: 'building', buildable: CrystalMine, level: 1, planetId},
    {type: 'building', buildable: MetalMine, level: 5, planetId},
    {type: 'building', buildable: CrystalMine, level: 2, planetId},
    {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
    {type: 'building', buildable: CrystalMine, level: 3, planetId},
    {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
    {type: 'building', buildable: MetalMine, level: 6, planetId},
    {type: 'building', buildable: CrystalMine, level: 4, planetId},
    {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
    {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
    {type: 'building', buildable: CrystalMine, level: 5, planetId},
    {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
    {type: 'building', buildable: ResearchLab, level: 1, planetId},
    {type: 'building', buildable: CrystalMine, level: 6, planetId},
    {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
    {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
    {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
    {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
    {type: 'building', buildable: Shipyard, level: 1, planetId},
    {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
    {type: 'building', buildable: Shipyard, level: 2, planetId},
    {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
  ];
}
export function getGoodBuildOrders(planetId: PlanetId): BuildItem[][] {
  return [
    [
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 6, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 8, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 7, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: CrystalMine, level: 7, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 8, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 8, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'building', buildable: CrystalMine, level: 7, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
    [
      {type: 'building', buildable: CrystalMine, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 2, planetId},
      {type: 'building', buildable: MetalMine, level: 3, planetId},
      {type: 'building', buildable: CrystalMine, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 1, planetId},
      {type: 'building', buildable: MetalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 2, planetId},
      {type: 'building', buildable: CrystalMine, level: 4, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 3, planetId},
      {type: 'building', buildable: MetalMine, level: 6, planetId},
      {type: 'building', buildable: ResearchLab, level: 1, planetId},
      {type: 'building', buildable: CrystalMine, level: 5, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 4, planetId},
      {type: 'building', buildable: MetalMine, level: 7, planetId},
      {type: 'building', buildable: DeuteriumSynthesizer, level: 5, planetId},
      {type: 'building', buildable: CrystalMine, level: 6, planetId},
      {type: 'building', buildable: CrystalMine, level: 7, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 1, planetId},
      {type: 'building', buildable: RoboticsFactory, level: 2, planetId},
      {type: 'technology', buildable: EnergyTechnology, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 1, planetId},
      {type: 'building', buildable: Shipyard, level: 1, planetId},
      {type: 'technology', buildable: CombustionDrive, level: 2, planetId},
      {type: 'building', buildable: Shipyard, level: 2, planetId},
      {type: 'ship', buildable: SmallCargo, quantity: 1, planetId},
    ],
  ];
}
